name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Debug - List files before install
        run: ls -la
          
      - name: Install dependencies
        run: npm install
        
      - name: Debug - Check Vite installation
        run: |
          echo "Checking if Vite is installed:"
          npm list vite
          echo "Checking package.json:"
          cat package.json
          
      - name: Build with verbose logging
        run: |
          echo "Running build command:"
          npm run build --verbose
          
      - name: Debug - List directory contents after build
        run: |
          echo "Current directory:"
          ls -la
          echo "Checking if dist directory exists:"
          ls -la dist || echo "dist directory does not exist"
          
      - name: Create dist directory if it doesn't exist
        run: mkdir -p dist
        
      - name: Create a test file if dist is empty
        run: |
          if [ -z "$(ls -A dist)" ]; then
            echo "Dist directory is empty, creating a test file"
            echo "<html><body><h1>Test Page</h1></body></html>" > dist/index.html
          fi
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
